// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return FirebaseOptions(
        apiKey: 'AIzaSyDp6CcU_L3X-jj11DRDCRNsWeMDPC3BE3U',
        appId: '1:931105313146:web:c921617ed4bfcc16d246c3',
        messagingSenderId: '931105313146',
        projectId: 'drone-match-5469f',
        authDomain: 'drone-match-5469f.firebaseapp.com',
        storageBucket: 'drone-match-5469f.appspot.com',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANXgacH4UihOCFwgEaGfbYdebL0HmZpJg',
    appId: '1:446371293238:web:43611c99dd858bc4309097',
    messagingSenderId: '446371293238',
    projectId: 'meet-christ-app',
    authDomain: 'meet-christ-app.firebaseapp.com',
    storageBucket: 'meet-christ-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHpFxhMmpvlfsDChVZ3N-WG5XX3c534IA',
    appId: '1:446371293238:android:7694f2f256ead5c1309097',
    messagingSenderId: '446371293238',
    projectId: 'meet-christ-app',
    storageBucket: 'meet-christ-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHpFxhMmpvlfsDChVZ3N-WG5XX3c534IA',
    appId: '1:446371293238:android:7694f2f256ead5c1309097',
    messagingSenderId: '446371293238',
    projectId: 'meet-christ-app',
    storageBucket: 'meet-christ-app.firebasestorage.app',
  );
}
